<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFISKUzT\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFISKUzT/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFISKUzT.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFISKUzT\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFISKUzT\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FISKUzT',
    'container.build_id' => '795014a6',
    'container.build_time' => 1543188493,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFISKUzT');
