<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOZJ84kA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOZJ84kA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOZJ84kA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOZJ84kA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerOZJ84kA\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'OZJ84kA',
    'container.build_id' => 'fc5e1637',
    'container.build_time' => 1542031753,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOZJ84kA');
